      - image:  dosko64/worker
        name:  worker
        command: ["./bin/worker"]
        args: ["-loglever=DEBUG"]
        resources:
          requests:
            cpu: "0.5"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 9000
          initialDelaySeconds: 120
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 9000
          initialDelaySeconds: 60
          timeoutSeconds: 10
