apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: dosko64/goweb:0.1