kind: Service
apiVersion: v1
metadata:
  name:  worker
spec:
  selector:
    app:  worker
  type: LoadBalancer
  # type: ClusterIP | NodePort | LoadBalancer
  ports:
  - name: web
    port: 8080
    targetPort: 8080
  - name: admin
    port: 9090
    targetPort: 9090

